name: deploy to S3
on:
  push:
      branches:
        - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Build
        run: |
          npm i -g yarn
          yarn
          yarn build
          mv build obs-what-time-is-it-now
          mkdir build
          mv obs-what-time-is-it-now/ build/

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp ./build/ s3://heppokofrontend.dev --recursive --region ap-northeast-1 
